push again

diff --git a/.github/workflows/bucketListPipe.yaml b/.github/workflows/bucketListPipe.yaml
--- a/.github/workflows/bucketListPipe.yaml
+++ b/.github/workflows/bucketListPipe.yaml
@@ -348,13 +348,13 @@ jobs:
       - name: Install Vite
         run: npm install -D vite
 
-      - name: Update front-end config
-        run: |
-          sed -i 's/LB_DNS/${{ secrets.TF_LB_DNS }}/g' src/home.jsx
-          if [ $? -ne 0 ]; then
-            echo "Error: Failed to update src/home.jsx"
-            exit 1
-          fi
+      # - name: Update front-end config
+      #   run: |
+      #     sed -i 's/LB_DNS/${{ secrets.TF_LB_DNS }}/g' src/home.jsx
+      #     if [ $? -ne 0 ]; then
+      #       echo "Error: Failed to update src/home.jsx"
+      #       exit 1
+      #     fi
 
       - name: Authenticate with GitHub CLI
         env: 
@@ -375,8 +375,8 @@ jobs:
       - name: Build application
         run: npx vite build
         env:
-          VITE_APP_BASE_URL: ${{secrets.TF_LB_DNS}}
-          #VITE_APP_BASE_URL: ${{secrets.TF_s3_frontend_url}}
+          #VITE_APP_BASE_URL: ${{secrets.TF_LB_DNS}}
+          VITE_APP_BASE_URL: ${{secrets.TF_s3_frontend_url}}
           VITE_APP_ENVIRONMENT: production
 
       - name: Configure AWS credentials
